# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('constellation', models.CharField(blank=True, max_length=50, null=True)),
                ('galaxy_type', models.CharField(max_length=50)),
                ('diameter', models.CharField(max_length=50)),
                ('num_of_starts', models.CharField(max_length=50)),
                ('mass', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='')),
                ('mass', models.CharField(max_length=50)),
                ('num_of_moons', models.PositiveIntegerField()),
                ('planet_type', models.CharField(max_length=50)),
                ('transit_time', models.CharField(max_length=50)),
                ('rotation_period', models.CharField(max_length=50)),
                ('distance_from_star', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlanetarySystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('constellation', models.CharField(blank=True, max_length=50, null=True)),
                ('star_temperature', models.CharField(max_length=50)),
                ('star_type', models.CharField(max_length=50)),
                ('star_mass', models.CharField(max_length=50)),
                ('star_radius', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='')),
                ('galaxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmox.Galaxy')),
            ],
        ),
        migrations.AddField(
            model_name='planet',
            name='planetary_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmox.PlanetarySystem'),
        ),
    ]
